version: 2.1

orbs:
 android: circleci/android@0.2.1

references:
 cache_key: &cache_key
   key: jars-{{ checksum "build.gradle" }}-{{ checksum  "app/build.gradle" }}-{{ checksum "gradle/wrapper/gradle-wrapper.properties" }}

config_android: &config_android
 working_directory: ~/code
 docker:
   - image: circleci/android:api-30

 environment:
   JVM_OPTS: -Xmx3200m

build_test: &build_test
 <<: *config_android
 steps:
   - checkout
   - restore_cache:
       <<: *cache_key
   - run:
      name: chmod permissions
      command: chmod +x ./gradlew
   - run:
       name: Download Dependencies
       command: ./gradlew androidDependencies

   - save_cache:
       <<: *cache_key
       paths:
         - ~/.gradle/caches
         - ~/.gradle/wrapper

   - run:
       name: Build app
       command: ./gradlew build

deploy_debug_to_firebase: &deploy_debug_to_firebase
 <<: *config_android
 steps:
   - checkout
   - run:
       name: Build debug
       command: ./gradlew :app:assembleDebug

   - run:
       name: Install Firebase CLI
       command: |
         curl -sL https://firebase.tools | bash

   - run:
       name: Upload File APK Debug to Firebase App Distribution
       command: firebase appdistribution:distribute app/build/outputs/apk/debug/app-debug.apk --app $FIREBASE_APP_ID --token $FIREBASE_TOKEN_CLI --release-notes "Upload APK to Firebase"

jobs:
 build_test:
   <<: *build_test

 deploy_debug_to_firebase:
   <<: *deploy_debug_to_firebase

workflows:
 version: 2
 build_test_and_deploy:
   jobs:
     - build_test
     - deploy_debug_to_firebase:
         requires:
           - build_test
         filters:
           branches:
             only: import_circle_ci_demo